[package]
name = "tic_tac_toe"
type = "contract"
authors = [""]
compiler_version = ">=0.19.0"

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.21.0", directory="yarn-project/aztec-nr/aztec" }
